### ISSUE TITLE
CI policy seems to need ListStackResources

### ISSUE THREAD

**Issue by declension** [FormidableLabs/terraform-aws-serverless#26]
Hi. Not sure if I'm doing something wrong here...

###  Assumptions
 * A Serverless project with just static content (no service)
 * Use Serverless `1.39.1`, `serverless-s3-sync`, and newish Terraform with `0.1.0` of this module

### Steps
 * Set up all Terraform stuff for the `ci` environment / stage
 * Deploy first time to `ci` stage as an admin, locally, verifying the stack reported is `my-service-name-ci`
 * Push changes to CI on the project, which is configured as `--stage ci` and also to use a user which is a member of the `my-service-name-ci-ci` group, created by the module..

### Expected
Success.

### Actual
Getting an error about needing `ListStackResources` permissions (but these only exist on :

```bash
$ yarn sls deploy --stage ci --subfolder "$CI_ENVIRONMENT_NAME_SLUG"
yarn run v1.13.0
...
  Serverless Error ---------------------------------------
 
  User: arn:aws:iam::*********:user/my-user-name is not authorized to perform: cloudformation:ListStackResources on resource: arn:aws:cloudformation:us-east-1:********:stack/my-service-name-ci/*
```

**Comment by ryan-roemer** [comment]
That sounds like it should work. Would you be able to paste your terraform configuration into this ticket? And if possible the serverless  config too? Anything you can paste, would be helpful! Thanks!

**Comment by declension** [comment]
Thanks, and sure. It's a bit abstracted / contained within some other stuff but the TF is roughly:

```hcl
module "serverless" {
  source = "FormidableLabs/serverless/aws"

  region       = "${var.aws_region}"
  service_name = "${var.service_name}"
  stage        = "${var.environment}"
  sls_service_name = "${var.service_name}"
}
```
and the SLS is 
```yaml
service: my-service-name
frameworkVersion: ">1.26.0"

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'ci'}

custom:
  subfolder: ${opt:subfolder, ''}
  bucketName: my-bucket-name-${opt:stage, 'ci'}
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      bucketPrefix: ${self:custom.subfolder}
      localDir: dist/

plugins:
  - serverless-s3-sync

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: AssetsBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                  "arn:aws:s3:::",
                  {
                    "Ref": "AssetsBucket"
                  },
                  "/*"
                ]
                ]
```
