### ISSUE TITLE
admin policy needs s3:PutEncryptionConfiguration permission

### ISSUE THREAD

**Issue by shrugs** [FormidableLabs/terraform-aws-serverless#33]
It seems like the admin role needs the `s3:PutEncryptionConfiguration` permission as well. 

Here is the full list of permissions a serverless-deploying agent might need: https://gist.github.com/ServerlessBot/7618156b8671840a539f405dea2704c8 — might be worth mentioning that your serverless agent may need way more permissions than this module provides by default (depending on which resources are managed with serverless and which are managed with terraform)

from the serverless cli:
```
  An error occurred: ServerlessDeploymentBucket - API: s3:SetBucketEncryption Access Denied.
```
[note: `SetBucketEncryption` is actually `PutEncryptionConfiguration`](https://forums.aws.amazon.com/thread.jspa?messageID=827867)

---

A workaround is to simply add that permission to your user/group/policy/whatever ad-hoc.

```tf
resource "aws_iam_group_policy" "additional_admin_policy" {
  name  = "tf-${var.service_name}-${var.stage}-additional-admin-policy"
  group = "tf-${var.service_name}-${var.stage}-admin"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:PutEncryptionConfiguration"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}
```

**Comment by ryan-roemer** [comment]
Do you have a reproduction for what `serverless.yml` or AWS-native configuration causes this?

Our long term plan is enhancements like `xray` for specific scenarios that a minimal sls app doesn't have. Or simple flags in root module / default support depending on how wide the permission is...

**Comment by shrugs** [comment]
here's my `serverless.yml` (random details redacted). perhaps it's the `ssm` environment injection?

```yaml
service: sls-${self:custom.service}

package:
  excludeDevDependencies: true
  exclude:
    - "**/node_modules/.cache/**"
    - "**/node_modules/aws-sdk/**" # included on Lambda.
    - "**/node_modules/.yarn-integrity"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  profile: sls-${self:custom.service}-${self:custom.stage}
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  timeout: 30 # seconds (`300` max)
  memorySize: 128 # MB value (`1024` default)
  vpc:
    securityGroupIds:
      - sg-1234567890
    subnetIds:
      - subnet-1234567890
      - subnet-1234567890
      - subnet-1234567890
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:us-east-1:1234567890:table/issues"
        - "arn:aws:dynamodb:us-east-1:1234567890:table/receipts"
    - Effect: Allow
      Action:
        - rds-data:*
      Resource:
        - "arn:aws:rds:us-east-1:1234567890:cluster:*"
  environment:
    STAGE: ${self:custom.stage}
    SERVICE_NAME: ${self:custom.service}
    DB_HOSTNAME: ${ssm:DFT_DB_HOSTNAME}
    DB_USERNAME: ${ssm:DFT_DB_USERNAME}
    DB_PASSWORD: ${ssm:DFT_DB_PASSWORD}
    DB_PORT: ${ssm:DFT_DB_PORT}

functions:
  my_function:
    handler: src/my_function.handler

custom:
  service: ${env:SERVICE_NAME}
  region: ${opt:region, env:AWS_REGION}
  stage: ${opt:stage, env:STAGE}

```
