### ISSUE TITLE
how to use own serverless.yml?

### ISSUE THREAD

**Issue by Rudya93** [FormidableLabs/terraform-aws-serverless#71]
Hello team, how I can use my own serverless.yml with your module? Or there is no such functionality, and you can use only your predefined yaml?

**Comment by ryan-roemer** [comment]
Hi @Rudya93 

So you use your own `serverless.yml` and just make sure to bring in the Lambda role from this module (which is exported via CloudFormation). As the docs say, pretty much just:

```yaml
provider:
  # ...
  role:
    Fn::ImportValue: tf-${self:custom.service}-${self:custom.stage}-LambdaExecutionRoleArn
```

Here are two examples of serverless configs that use this module:
- Simple: https://github.com/FormidableLabs/aws-lambda-dogs/blob/main/serverless.yml
- Complex: https://github.com/FormidableLabs/aws-lambda-serverless-reference/blob/master/serverless.yml

Hope that helps!
