### ISSUE TITLE
Feature/Option: Xray

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/terraform-aws-serverless#9]
Dependencies:

- IAM

```yml
# TODO(IamPolicyAdmin): Xray: view traces
- Effect: Allow
  Action:
  - xray:BatchGetTraces
  - xray:GetServiceGraph
  - xray:GetTraceGraph
  - xray:GetTraceSummaries
  Resource:
  # Must be wildcard.
  # https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awsxray.html
  # https://docs.aws.amazon.com/xray/latest/devguide/xray-permissions.html#xray-permissions-managedpolicies
  - "*"
# TODO(IamPolicyLambdaExecution): Xray: upload traces
- Effect: Allow
  Action:
  - xray:PutTraceSegments
  - xray:PutTelemetryRecords
  Resource:
  # Must be wildcard.
  # https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awsxray.html
  # https://docs.aws.amazon.com/xray/latest/devguide/xray-permissions.html#xray-permissions-managedpolicies
  - "*"
```
